### ISSUE TITLE
custom login form

### ISSUE THREAD

**Issue by devMls** [andreacomo/tomcat-jwt-security#5]
Hi.

First of all, this projects looks great!.

I am thinking in use it in my app, but i have a cuestion. I understand that i can have my custom login form that will be not protected and it must generate the x-auth header.

But if a user try to access to a protected resource without the header.... 
my app will show the awfull basic login popup? is it possible instead redirect to my customized login dialog ?

**Comment by andreacomo** [comment]
Hi,
sorry for delay but I missed issue notification via mail.
I think popup is related to "BASIC" authentication specified in `web.xml`: have you tried to remove `realm-name` tag? Maybe login popup will disappear (I hope).
Regarding redirect to login, this could be a nice feature, if you wanna make a PR :)

Please let me know if removing `realm-name` will work, otherwise I will investigate.

**Comment by andreacomo** [comment]
Hi,
just tried question about popup. Tomcat (tried on 8.0.21) is not showing any popup if you do not provide header in your request: it just return a standard 401 Tomcat page (which you can override from your `web.xml`).
I have a second thought about redirect to login: It's responsibility of client to decide what to do on 401. You can provide your custom 401 page in `web.xml` and show information you want to provide to user.

Hope these information can help.
Can I consider issue closed?
