### ISSUE TITLE
Token Generation

### ISSUE THREAD

**Issue by konkodi210** [andreacomo/tomcat-jwt-security#7]
First of all thanks for creating this project. It really helped me to implement Access token in tomcat.

I have some area of improvements for this. At present to implement this feature in the project, I need register valve in tomcat and then need to make update on web application to create the auth header post authentication.  One problem I faced is I when used “UserDatabaseRealm” (using tomcat-user.xml) with BASIC authentication.  Even thought in the in web.xml, I said basic authentication, it never showed login popup. Instead it gave me error saying please login first.

Ideally anything do we with security should be handled by servlet container Realm. We should not be writing any code in web application related to security. In our case, once user authenticate with tomcat realm, JWTValue should generate the token if it does not exists. 

I have extended the JwtTokenValve class and added below code to auto generate the token if it does not exists. Let me know this enhancement is helpful. If you agree, we can update core classes.

@Override
public void invoke(Request request, Response response) throws IOException, ServletException {
  if(getToken(request) == null) {
    //if user is not logged in, propagate the request and let container authenticate
    if(request.getUserPrincipal() == null) {							
      this.getNext().invoke(request, response);
    }
    //for basic authentication, there will be some back and forth. Hence check once more of user is validated by container.
    if(request.getUserPrincipal() != null){
      JwtTokenBuilder tokenBuilder = JwtTokenBuilder.create(secret);
      String token = tokenBuilder.userId(request.getUserPrincipal().getName())
          .roles(Arrays.asList("admin"))
          .expirySecs(1800)
          .build();
      response.addHeader(JwtConstants.AUTH_HEADER, token);				
    }
  }else {	
    //if token is found, validate the token
    super.invoke(request, response);
  }
}

**Comment by andreacomo** [comment]
Hi and thank you for using this project. Sorry for late response but I totally miss the notification of your request.
The idea is good, but I think that the way an application generates the token cannot be the same for everyone (in your example you hardcoded roles for instance) and maybe someone would add custom claims in token useful to its clients. This is why I think is responsibility of every application to handle login and token generation.

About your problem that the popup never shows up, it's actually intentional because the valve is designed for working as backend API, and no user interaction is expected.

I Hope I responded your considerations.
